# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mocklook' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mocklook
  pod 'SwiftSky', '~> 1.3'

  target 'MocklookTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
